services:
  vpn:
    image: registry.home.local/openvpn-client:v0.0.1
    # build: .
    container_name: openvpn-client
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun:/dev/net/tun
    environment:
     #- SUBNETS=192.168.10.0/24
      - HTTP_PROXY=on
      - SOCKS_PROXY=on
      - KILL_SWITCH=nftable
      - SSHD=on
      - SSH_PASSWORD=password  
    # - PROXY_USERNAME_SECRET=username # <-- If used, these must match the name of a
    # - PROXY_PASSWORD_SECRET=password # <-- secret (NOT the file used by the secret)
    volumes:
      - ./ovpn:/data/vpn
      - ~/.ssh:/home/ovpn/.ssh # <-- ssh keys
      
    ports:
    - 1080:1080
    - 8088:8080
    - 2222:22
